swagger: "2.0"
info:
  description: "Create a new appointment"
  version: "1.0.0"
  title: "Create Appointment"
security:
  - Bearer: []
tags:
  - "appointments"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "Appointment object that needs to be added"
    required: true
    schema:
      type: object
      properties:
        doctor_id:
          type: string
          example: "60d0fe4f5311236168a109ca"
        date_time:
          type: string
          example: "2024-06-07 10:30:00"
responses:
  201:
    description: "Appointment created successfully"
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Appointment created successfully"
  400:
    description: "Invalid date format or date and time in the past"
  401:
    description: "Token is missing or invalid"
