swagger: "2.0"
info:
  description: "Get details of an appointment"
  version: "1.0.0"
  title: "Get Appointment"
security:
  - Bearer: []
tags:
  - "appointments"
produces:
  - "application/json"
parameters:
  - name: "appointment_id"
    in: "path"
    required: true
    type: "string"
    description: "ID of the appointment"
responses:
  200:
    description: "Details of the appointment"
    schema:
      type: object
      properties:
        _id:
          type: string
        user:
          type: string
        doctor:
          type: string
        date_time:
          type: string
  404:
    description: "Appointment not found"
  401:
    description: "Token is missing or invalid"
