swagger: "2.0"
info:
  description: "Admin only route"
  version: "1.0.0"
  title: "Admin Only"
security:
  - Bearer: []
tags:
  - "auth"
produces:
  - "application/json"
responses:
  200:
    description: "Welcome, admin!"
  403:
    description: "You do not have permission to access this resource"
