swagger: "2.0"
info:
  description: "API to change the password of the user"
  version: "1.0.0"
  title: "Change Password"
security:
  - Bearer: []
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "Object containing the current and new password of the user"
    required: true
    schema:
      type: object
      properties:
        current_password:
          type: string
          example: "currentPassword123"
        new_password:
          type: string
          example: "newPassword123"
responses:
  200:
    description: "Password updated successfully"
  401:
    description: "Current password is incorrect or token is missing or invalid"
  404:
    description: "User not found"
