swagger: "2.0"
info:
  description: "Change user password"
  version: "1.0.0"
  title: "Change Password"
security:
  - Bearer: []
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "Change password data"
    required: true
    schema:
      type: object
      properties:
        current_password:
          type: string
          example: "oldpassword123"
        new_password:
          type: string
          example: "newpassword123"
responses:
  200:
    description: "Password updated successfully"
  401:
    description: "Current password is incorrect"
