swagger: "2.0"
info:
  description: "API to confirm the password reset process using a token and set a new password"
  version: "1.0.0"
  title: "Confirm Reset Password"
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "Object containing the reset token and new password"
    required: true
    schema:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        new_password:
          type: string
          example: "newPassword123"
responses:
  200:
    description: "Password has been reset successfully"
  400:
    description: "Invalid token or token has expired"
