swagger: "2.0"
info:
  description: "Confirm reset password"
  version: "1.0.0"
  title: "Confirm Reset Password"
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "New password data with token"
    required: true
    schema:
      type: object
      properties:
        token:
          type: string
          example: "reset-token"
        new_password:
          type: string
          example: "newpassword123"
responses:
  200:
    description: "Password has been reset successfully"
  400:
    description: "Invalid token or token has expired"
