swagger: "2.0"
info:
  description: "API to initiate the password reset process by sending a reset email to the user"
  version: "1.0.0"
  title: "Forgot Password"
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "Email object containing the user's email address"
    required: true
    schema:
      type: object
      properties:
        email:
          type: string
          example: "user@example.com"
responses:
  200:
    description: "Password reset email sent successfully"
  404:
    description: "User not found"
