swagger: "2.0"
info:
  description: "Forgot password"
  version: "1.0.0"
  title: "Forgot Password"
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "User email for password reset"
    required: true
    schema:
      type: object
      properties:
        email:
          type: string
          example: "user@example.com"
responses:
  200:
    description: "Password reset email sent"
  404:
    description: "User not found"
