swagger: "2.0"
info:
  description: "Search for appointments based on criteria"
  version: "1.0.0"
  title: "Search Appointments"
security:
  - Bearer: []
tags:
  - "appointments"
produces:
  - "application/json"
parameters:
  - name: "doctor_id"
    in: "query"
    required: false
    type: "string"
    description: "Doctor ID to search for appointments"
  - name: "date_time"
    in: "query"
    required: false
    type: "string"
    description: "Date and time to search for appointments (format: YYYY-MM-DDTHH:MM:SS)"
responses:
  200:
    description: "List of appointments matching the criteria"
    schema:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
            example: "60d0fe4f5311236168a109ca"
          user:
            type: string
            example: "user@example.com"
          doctor:
            type: string
            example: "doctor@example.com"
          date_time:
            type: string
            example: "2024-06-07 10:30:00"
          status:
            type: string
            example: "Scheduled"
  400:
    description: "Invalid search criteria"
  401:
    description: "Token is missing or invalid"
  404:
    description: "No appointments found"
