swagger: "2.0"
info:
  description: "Send email verification"
  version: "1.0.0"
  title: "Send Verification Email"
security:
  - Bearer: []
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "User email to send verification"
    required: true
    schema:
      type: object
      properties:
        email:
          type: string
          example: "user@example.com"
responses:
  200:
    description: "Verification email sent"
  404:
    description: "User not found"
