swagger: "2.0"
info:
  description: "Setup MFA"
  version: "1.0.0"
  title: "Setup MFA"
security:
  - Bearer: []
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "MFA settings"
    required: true
    schema:
      type: object
      properties:
        mfa_enabled:
          type: boolean
          example: true
responses:
  200:
    description: "MFA setting updated successfully"
  404:
    description: "User not found"
