swagger: "2.0"
info:
  description: "Update doctor availability"
  version: "1.0.0"
  title: "Update Availability"
security:
  - Bearer: []
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "Doctor availability object"
    required: true
    schema:
      type: object
      properties:
        availability:
          type: array
          items:
            type: string
            example: "Monday 09:00-17:00"
responses:
  200:
    description: "Availability updated successfully"
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Availability updated successfully"
  404:
    description: "User not found"
    schema:
      type: object
      properties:
        message:
          type: string
          example: "User not found"
  401:
    description: "Token is missing or invalid"
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Token is missing or invalid"
