swagger: "2.0"
info:
  description: "Update an existing appointment"
  version: "1.0.0"
  title: "Update Appointment"
security:
  - Bearer: []
tags:
  - "appointments"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - name: "appointment_id"
    in: "path"
    required: true
    type: "string"
    description: "ID of the appointment"
  - in: "body"
    name: "body"
    description: "Appointment object that needs to be updated"
    required: true
    schema:
      type: object
      properties:
        doctor:
          type: string
          example: "Dr. Smith"
        date_time:
          type: string
          example: "2024-06-10 14:30:00"
responses:
  200:
    description: "Appointment updated successfully"
  400:
    description: "Invalid date format"
  401:
    description: "Token is missing or invalid"
  404:
    description: "Appointment not found"
