swagger: "2.0"
info:
  description: "Register a new user"
  version: "1.0.0"
  title: "User Registration"
security:
  - Bearer: []
tags:
  - "auth"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - in: "body"
    name: "body"
    description: "User object that needs to be added"
    required: true
    schema:
      type: object
      required:
        - email
        - password
        - role
      properties:
        email:
          type: string
          example: "user@example.com"
        password:
          type: string
          example: "password123"
        username:
          type: string
          example: "johndoe"
        phone:
          type: string
          example: "1234567890"
        role:
          type: string
          example: "patient"
        specialty:
          type: string
          example: "Cardiology"
        availability:
          type: array
          items:
            type: string
          example: ["Monday 10:00-14:00", "Wednesday 12:00-16:00"]
        profile_picture:
          type: string
          example: "http://example.com/path/to/profile_picture.jpg"
        mfa_enabled:
          type: boolean
          example: false
        email_verified:
          type: boolean
          example: false
        approved:
          type: boolean
          example: true
responses:
  201:
    description: "User registered successfully"
    schema:
      type: object
      properties:
        token:
          type: string
          example: "JWT token"
        refresh_token:
          type: string
          example: "Refresh JWT token"
  400:
    description: "User already exists"
